#
# Makefile for nfc devices
#
obj-$(CONFIG_CXD2235AGC_NFC_FELICA) += felica_master.o felica_cen.o felica_pon.o \
								felica_int.o felica_rfs.o felica_rws.o \
								snfc_avail.o snfc_hsel.o snfc_intu.o
obj-$(CONFIG_S7760A) +=s7760a.o								
							 